name: basic_food_delivery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.1
  dot_curved_bottom_nav: ^0.0.2
  carousel_slider: ^5.1.1
  liquid_swipe: ^3.1.0
  flutter_rounded_progress_bar: ^0.3.2
  intl: ^0.19.0
  equatable: ^2.0.5
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/banner/
    - assets/branding/
    - assets/CategoryItems/
    - assets/Figma UI/
    - assets/FootItems/
    - assets/logo/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_updated.png"

flutter_native_splash:
  color: "#FD6347"
  image: assets/logo/logo.png
  android: true
  ios: true

  android_12:
    color: "#FD6347"
    image: assets/logo/logo_android_12_fifth.png
#    branding: assets/logo/logo.png
#    image: assets/Figma UI/SplashScreen.png
#    color: "#ffffff"
    icon_background_color: "#FD6347"
